name: Run World Development Indicators Connector

on:
  workflow_dispatch:

jobs:
  run-connector:
    runs-on: ubuntu-latest
    timeout-minutes: 360  # 6 hours for downloading all indicators
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 1  # Shallow clone for speed
    
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        cache: 'pip'  # Built-in pip caching
    
    - name: Install uv for fast package installation
      run: pip install uv
    
    - name: Install dependencies
      run: |
        # UV can now read pyproject.toml directly
        uv pip install --system .
    
    - name: Run connector
      run: |
        python -u main.py
      env:
        PYTHONUNBUFFERED: "1"
        R2_ACCESS_KEY_ID: ${{ secrets.R2_ACCESS_KEY_ID }}
        R2_SECRET_ACCESS_KEY: ${{ secrets.R2_SECRET_ACCESS_KEY }}
        R2_ENDPOINT_URL: ${{ secrets.R2_ENDPOINT_URL }}
        R2_BUCKET_NAME: ${{ secrets.R2_BUCKET_NAME }}